### Members' Full name:

- Nguyen Mai Dinh, Le - 300312139
- Ruiz, Ricardo - 300387021
- Jimmy, Suwarly - 300361475
- Hugh, Tran - 300394597

# Part A. Planning

## FAQBot Design using Elasticsearch

- Each row in the dataset is indexed as a document with two fields: **question** and **answer**.  
- Elasticsearch analyzes and tokenizes the text, enabling both **keyword matching** and **semantic relevance**.

### Retrieval Strategy
- Use a **multi-field search** on both *question* and *answer*.  
- Assign higher weight to the **question field** to prioritize topic relevance.  
- Apply **phrase matching** on the question to boost results that closely match user input.  

### Query Process
- User submits a question.  
- Elasticsearch retrieves and ranks relevant FAQ documents based on similarity score.  
- The **top-ranked result** (or top-k results) is returned as the answer.

# Part B. Basic Model

### 1. Import Library + Data Loading

In [1]:
#pip install -q -U google-genai

In [2]:
# Import all libraries for Parts B, C and D in one cell
import os
from google import genai
import time
from google.genai import types
import re
import glob
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from IPython.display import display
from pathlib import Path

# Part B
try:
    from elasticsearch import Elasticsearch
except Exception:
    Elasticsearch = None

# Part C
try:
    import spacy
    from sklearn.metrics.pairwise import cosine_similarity
except Exception:
    spacy = None
    cosine_similarity = None

# part D
from google import genai

In [3]:
df1 = pd.read_csv("faq.csv")
df2 = pd.read_csv("faq1.csv")
df3 = pd.read_csv("faq2.csv")
df4 = pd.read_csv("faq3.csv")
df5 = pd.read_csv("faq4.csv")
df6 = pd.read_csv("faq5.csv")
df7 = pd.read_csv("faq6.csv")
df8 = pd.read_csv("faq7.csv")
df9 = pd.read_csv("faq8.csv")
df10 = pd.read_csv("faq9.csv")
df11 = pd.read_csv("faq10.csv")

df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11 ], ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  114 non-null    object
 1   answer    114 non-null    object
dtypes: object(2)
memory usage: 1.9+ KB

### 2. Search Engine Building

In [4]:
# Connection settings
INDEX_NAME = "douglas_faq_basic"

ES_HOST = "localhost"
ES_PORT = 9200
ES_SCHEME = "https"
ES_USERNAME = "elastic"
ES_PASSWORD = "NEl9eD+gUB7v+XOgGEu_"

es = None
es_ready = False

if Elasticsearch is None:
    print("Elasticsearch library is not installed in this environment.")
else:
    try:
        es = Elasticsearch(
            [{"host": ES_HOST, "port": ES_PORT, "scheme": ES_SCHEME}],
            basic_auth=(ES_USERNAME, ES_PASSWORD),
            verify_certs=False
        )
        if es.ping():
            es_ready = True
            print("Connected to Elasticsearch successfully.")
        else:
            print("Could not connect to Elasticsearch. Please make sure the local server is running.")
    except Exception as e:
        print("Elasticsearch client/server is not ready yet.")
        print("Details:", e)

Connected to Elasticsearch successfully.

In [5]:
# Create a new index
if es_ready:
    if es.indices.exists(index=INDEX_NAME):
        es.indices.delete(index=INDEX_NAME)

    mapping = {
        "mappings": {
            "properties": {
                "question": {"type": "text"},
                "answer": {"type": "text"}
            }
        }
    }

    es.indices.create(index=INDEX_NAME, body=mapping)
    print(f"Index '{INDEX_NAME}' created.")
else:
    print("Skipping index creation because Elasticsearch is not ready.")

Index 'douglas_faq_basic' created.

In [6]:
# Index all FAQ documents
if es_ready:
    for i, row in df.iterrows():
        doc = {
            "question": row["question"],
            "answer": row["answer"]
        }
        es.index(index=INDEX_NAME, id=i + 1, body=doc)

    es.indices.refresh(index=INDEX_NAME)
    res = es.search(index=INDEX_NAME, body={"query": {"match_all": {}}})
    print("Indexing complete.")
    print("Total documents in the index:", res["hits"]["total"]["value"])
else:
    print("Skipping document indexing because Elasticsearch is not ready.")

Indexing complete.
Total documents in the index: 114

In [7]:
# Search function for Part B
def search_faq(user_query, top_k=5):
    if not es_ready:
        return pd.DataFrame(columns=["rank", "score", "question", "answer"])

    body = {
        "size": top_k,
        "query": {
            "bool": {
                "should": [
                    {
                        "multi_match": {
                            "query": user_query,
                            "fields": ["question^2", "answer"]
                        }
                    },
                    {
                        "match_phrase": {
                            "question": {
                                "query": user_query,
                                "boost": 2
                            }
                        }
                    }
                ]
            }
        }
    }

    response = es.search(index=INDEX_NAME, body=body)

    rows = []
    for rank, hit in enumerate(response["hits"]["hits"], start=1):
        rows.append({
            "rank": rank,
            "score": hit["_score"],
            "question": hit["_source"]["question"],
            "answer": hit["_source"]["answer"]
        })

    return pd.DataFrame(rows)

In [8]:
# Example search
sample_query = "How can I apply to  Douglas College?"
display(search_faq(sample_query, top_k=5))

,rank,score,question,answer
0,1,23.595293,How do I apply to graduate from Douglas College?,Apply for graduation through myAccount under S...
1,2,20.429005,When can I apply for graduation at Douglas Col...,Students can apply for Winter (February) gradu...
2,3,20.085466,How many programs can I apply to?,You can indicate one program choice per applic...
3,4,13.541569,I am almost done my program. How do I apply to...,You should apply to graduate after you have en...
4,5,13.088499,How do I calculate my GPA for my Douglas Colle...,Use the GPA calculator to determine your curre...

### 3. Testing + Evaluation

#### 3.1. Precision@K Function + Testing + Evaluation function

In [9]:
def run_queries(es, index_name, queries, top_k=5):
    results = {}
    
    for q in queries:
        response = es.search(
            index=index_name,
            body={
                "query": {
                    "multi_match": {
                        "query": q,
                        "fields": ["question^2", "answer"]
                    }
                },
                "size": top_k
            }
        )
        
        docs = []
        for hit in response["hits"]["hits"]:
            docs.append(hit["_source"])
        
        results[q] = docs
    
    return results

def precision_at_k(relevance_list, k=1):
    return sum(relevance_list[:k]) / k

def evaluate_precision_at_1(relevance_judgments):
    scores = []
    
    for rels in relevance_judgments.values():
        p1 = precision_at_k(rels, k=1)
        scores.append(p1)
    
    avg_p1 = sum(scores) / len(scores)
    
    return scores, avg_p1

def evaluate_precision_at_k(relevance_judgments, k=5):
    scores = []
    
    for rels in relevance_judgments.values():
        pk = precision_at_k(rels, k=k)
        scores.append(pk)
    
    avg_pk = sum(scores) / len(scores)
    
    return scores, avg_pk

#### 3.2. 20 questions + Evaluation

**Ricardo**

5 questions:
- If I arrive late in Canada, can I study online first?,
- My health insurance will end soon. Who should I talk to?,
- I need help paying for school. Where can I ask about financial support?,
- If I get sick and miss class, how can I ask my instructor for help?,
- I want to transfer later to a university. Who can help me plan my courses?

In [10]:
# Testing questions

ricardo_questions = [
    "If I arrive late in Canada, can I study online first?",
    "My health insurance will end soon. Who should I talk to?",
    "I need help paying for school. Where can I ask about financial support?",
    "If I get sick and miss class, how can I ask my instructor for help?",
    "I want to transfer later to a university. Who can help me plan my courses?"
]

ricardo_results = []

for query in ricardo_questions:
    response = es.search(
        index=INDEX_NAME,
        query={
            "match": {
                "question": query
            }
        },
        size=1
    )

    hits = response["hits"]["hits"]

    if len(hits) > 0:
        top_hit = hits[0]["_source"]
        top_question = top_hit.get("question", "N/A")
        top_answer = top_hit.get("answer", "N/A")
    else:
        top_question = "No result found"
        top_answer = "No answer found"

    ricardo_results.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer
    })

# Ask for manual relevance with evidence
ricardo_relevance = {}

for item in ricardo_results:
    print("\n" + "="*80)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            ricardo_relevance[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate
ricardo_p1_scores, ricardo_avg_p1 = evaluate_precision_at_1(ricardo_relevance)

print("\nRicardo relevance judgments:")
print(ricardo_relevance)
print("\nRicardo Precision@1 for each query:", ricardo_p1_scores)
print("Ricardo Average Precision@1:", ricardo_avg_p1)

================================================================================
Query:
If I arrive late in Canada, can I study online first?

Top returned question:
I am in Canada, can I take online courses in the Winter 2022 semester?

Top returned answer:
Starting from Winter 2022 semester we strongly recommend that students who are inside Canada to complete in-person classes to meet post-graduation work permit eligibility requirements. You can review Immigration, Refugees, and Citizenship Canada (IRCC) updates on distance learning here.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
My health insurance will end soon. Who should I talk to?

Top returned question:
My medical insurance is expiring. What should I do?

Top returned answer:
If your medical insurance is expiring, now is the time to ensure you are covered. For information on medical insurance for international students, please visit this page for options.

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

================================================================================
Query:
I need help paying for school. Where can I ask about financial support?

Top returned question:
Paying for school and graduating without a huge debt

Top returned answer:
Investigate funding options and try to minimize your borrowing. Plan your finances now to avoid stress and uncertainty while you are a student. Live simply and inexpensively so that you can look forward to graduating without a huge debt.

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

================================================================================
Query:
If I get sick and miss class, how can I ask my instructor for help?

Top returned question:
If I am sick, are there alternatives to attend class/take exams online?

Top returned answer:
Decision regarding attendance is the discretion of individual instructors, and faculty are encouraged to be reasonable when dealing with absences. Students continue to have the responsibility to communicate when illness impacts their ability to meet the requirements of a class.   It is expected that we may have higher than normal absenteeism this semester, particularly in the first few weeks of classes. Instructors will do their best to be understanding of students’ situations. Any resources or ...

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

================================================================================
Query:
I want to transfer later to a university. Who can help me plan my courses?

Top returned question:
I'm interested in transferring to a university, how should I plan my courses?

Top returned answer:
Please review our University Transfer page for more information on how to plan for your transfer.  We encourage students to meet with a Student Success Advisor early to plan a successful transfer.

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

Ricardo relevance judgments:
{'If I arrive late in Canada, can I study online first?': [0], 'My health insurance will end soon. Who should I talk to?': [1], 'I need help paying for school. Where can I ask about financial support?': [1], 'If I get sick and miss class, how can I ask my instructor for help?': [1], 'I want to transfer later to a university. Who can help me plan my courses?': [1]}

Ricardo Precision@1 for each query: [0.0, 1.0, 1.0, 1.0, 1.0]
Ricardo Average Precision@1: 0.8

**Jimmy**

5 questions:
 - What is the best way to contact Enrollment Services?
 - How do I update my personal information?
 - Who do I contact if I have questions about Co-op?
 - What if I want to take a course from another university/college?
 - What happens if I withdraw from a course?

In [11]:
# Testing questions - Jimmy

Jimmy_questions = [
    "What is the best way to contact Enrollment Services?",
    "How do I update my personal information?",
    "Who do I contact if I have a questions about Co-op?",
    "What if I want to take a course from another university/college?",
    "What happens if I withdraw from a course?"
]

Jimmy_results = []

for query in Jimmy_questions:
    response = es.search(
        index=INDEX_NAME,
        query={
            "match": {
                "question": query
            }
        },
        size=1
    )

    hits = response["hits"]["hits"]

    if len(hits) > 0:
        top_hit = hits[0]["_source"]
        top_question = top_hit.get("question", "N/A")
        top_answer = top_hit.get("answer", "N/A")
    else:
        top_question = "No result found"
        top_answer = "No answer found"

    Jimmy_results.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer
    })

# Ask for manual relevance with evidence
Jimmy_relevance = {}

for item in Jimmy_results:
    print("\n" + "="*80)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            Jimmy_relevance[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate
Jimmy_p1_scores, Jimmy_avg_p1 = evaluate_precision_at_1(Jimmy_relevance)

print("\nJimmy relevance judgments:")
print(Jimmy_relevance)
print("\nJimmy Part B Precision@1 scores:", Jimmy_p1_scores)
print("Jimmy Part B Average Precision@1:", Jimmy_avg_p1)

================================================================================
Query:
What is the best way to contact Enrollment Services?

Top returned question:
What is the difference between the support services offered by counsellors, student success advisors and career coaches?

Top returned answer:
Review the statements below to determine who would be best able to assist you.  I am... I should talk to... I don’t know... I should contact... I want... I should ask... not sure which field of study or career would be best for me.  indecisive about my future life goals.  not doing well academically in my current program and wondering if I should change directions. not sure if I’m making good choices for my future. struggling to handle my course load and worried I will not be successful. feeling...

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
How do I update my personal information?

Top returned question:
How do I update my mailing address for graduation?

Top returned answer:
You can update your mailing address and phone number in myAccount under Personal Information. If you would like to update your name, complete a Name Change Request and submit it to Enrolment Services.

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

================================================================================
Query:
Who do I contact if I have a questions about Co-op?

Top returned question:
My International question wasn't answered by this FAQ. Who do I contact?

Top returned answer:
When contacting the international office, please include your full legal name and student ID for verification. For information on our online services please visit our online services page or you can contact us via webform.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
What if I want to take a course from another university/college?

Top returned question:
How do I apply to graduate from Douglas College?

Top returned answer:
Apply for graduation through myAccount under Student Records. It is recommended that you meet with your Student Success Advisor to ensure you are on track before applying.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
What happens if I withdraw from a course?

Top returned question:
What happens if I miss the graduation application deadline?

Top returned answer:
Students are required to submit an application to graduate in order to receive a Program Completion Letter. International students who miss the graduation application deadline must contact the Douglas College International Office immediately.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

Jimmy relevance judgments:
{'What is the best way to contact Enrollment Services?': [0], 'How do I update my personal information?': [1], 'Who do I contact if I have a questions about Co-op?': [0], 'What if I want to take a course from another university/college?': [0], 'What happens if I withdraw from a course?': [0]}

Jimmy Part B Precision@1 scores: [0.0, 1.0, 0.0, 0.0, 0.0]
Jimmy Part B Average Precision@1: 0.2

**Hugh**

5 questions:
- How can I submit my application?
- What do I need to pay for tuition?
- Where can I get advising help?
- How do I talk to a student advisor?
- What happens if I fail a course?

Testing using the pre-built testing function

Evaluation

In [12]:
# Testing questions - Hugh

hugh_questions = [
    "How can I submit my application?",
    "What do I need to pay for tuition?",
    "Where can I get advising help?",
    "How do I talk to a student advisor?",
    "What happens if I fail a course?"
]

hugh_results = []

for query in hugh_questions:
    response = es.search(
        index=INDEX_NAME,
        query={
            "match": {
                "question": query
            }
        },
        size=1
    )

    hits = response["hits"]["hits"]

    if len(hits) > 0:
        top_hit = hits[0]["_source"]
        top_question = top_hit.get("question", "N/A")
        top_answer = top_hit.get("answer", "N/A")
    else:
        top_question = "No result found"
        top_answer = "No answer found"

    hugh_results.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer
    })

# Ask for manual relevance with evidence
hugh_relevance = {}

for item in hugh_results:
    print("\n" + "="*80)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            hugh_relevance[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate
hugh_p1_scores, hugh_avg_p1 = evaluate_precision_at_1(hugh_relevance)

print("\nHugh relevance judgments:")
print(hugh_relevance)
print("\nHugh Part B Precision@1 scores:", hugh_p1_scores)
print("Hugh Part B Average Precision@1:", hugh_avg_p1)

================================================================================
Query:
How can I submit my application?

Top returned question:
How will COVID-19 impact processing of my immigration applications (study/work permits, permanent residence application, biometrics, etc.)?

Top returned answer:
To find the latest information on Immigration, Refugees and Citizenship Canada’s policy and service adjustments due to COVID-19, please review the International Student IRCC Coronavirus Disease: International Student page.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
What do I need to pay for tuition?

Top returned question:
Do I need to prepare anything for my appointment?

Top returned answer:
No, you do not need to prepare anything. However, we advise you to read the Information and Consent to Counsel Form prior to your session. Your counsellor will go over this when you arrive, so it will speed up the process if you are already familiar with it.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
Where can I get advising help?

Top returned question:
Where can I get more information on student loans, grants, awards, scholarships, and bursaries?

Top returned answer:
Please contact our Financial Aid department to get detailed information about these topics.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
How do I talk to a student advisor?

Top returned question:
How will failing a course affect my student loan?

Top returned answer:
To continue receiving financial aid, the Canada Student Financial Assistance Act, Canada Student Financial Assistance Program policy and StudentAid BC policy require you to maintain a satisfactory scholastic standing. More about this: https://studentaidbc.ca/maintain/responsibilities#scholastic-standing

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
What happens if I fail a course?

Top returned question:
What happens if I miss the graduation application deadline?

Top returned answer:
Students are required to submit an application to graduate in order to receive a Program Completion Letter. International students who miss the graduation application deadline must contact the Douglas College International Office immediately.

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

Hugh relevance judgments:
{'How can I submit my application?': [0], 'What do I need to pay for tuition?': [0], 'Where can I get advising help?': [0], 'How do I talk to a student advisor?': [0], 'What happens if I fail a course?': [0]}

Hugh Part B Precision@1 scores: [0.0, 0.0, 0.0, 0.0, 0.0]
Hugh Part B Average Precision@1: 0.0

##### ==> Judgements of the relevant of the answers:
 
- Hugh Part B Precision@1 scores: [0.0, 0.0, 0.0, 0.0, 0.0]
- Hugh Part B Average Precision@1: 0.0

**Demi**

Is there a deadline I need to follow when applying to Douglas College programs?

What happens if I don’t pay my tuition fees on time? Are there penalties?

How is my final grade determined, and can it be reviewed if I think it’s incorrect?

Can I book an appointment to discuss my course planning and academic goals?

What kind of mental health or counselling services are available for students?

In [13]:
# Testing questions

demi_questions = [
    "Is there a deadline I need to follow when applying to Douglas College programs?",
    "What happens if I don’t pay my tuition fees on time? Are there penalties?",
    "How is my final grade determined, and can it be reviewed if I think it’s incorrect?",
    "Can I book an appointment to discuss my course planning and academic goals?",
    "What kind of mental health or counselling services are available for students?"
]

demi_results = []

for query in demi_questions:
    response = es.search(
        index=INDEX_NAME,
        query={
            "match": {
                "question": query
            }
        },
        size=1
    )

    hits = response["hits"]["hits"]

    if len(hits) > 0:
        top_hit = hits[0]["_source"]
        top_question = top_hit.get("question", "N/A")
        top_answer = top_hit.get("answer", "N/A")
    else:
        top_question = "No result found"
        top_answer = "No answer found"

    demi_results.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer
    })

# Ask for manual relevance with evidence
demi_relevance = {}

for item in demi_results:
    print("\n" + "="*80)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            demi_relevance[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate
demi_p1_scores, demi_avg_p1 = evaluate_precision_at_1(demi_relevance)

print("\nDemi relevance judgments:")
print(demi_relevance)
print("\nDemi Precision@1 for each query:", demi_p1_scores)
print("Demi Average Precision@1:", demi_avg_p1)

================================================================================
Query:
Is there a deadline I need to follow when applying to Douglas College programs?

Top returned question:
I am out of the country, when should I come to BC and what is required by Douglas College?

Top returned answer:
Classes that are scheduled as “in-person” or “hybrid” require students to be here from the beginning of the semester. Unless your country has a travel ban and you are able to study online, you should plan to arrive in Canada at least 14 days before classes start to complete quarantine if required. Travel planning: a. You can travel to Canada as an international student if you have a valid study permit or have been approved for a study permit. b. Students travelling to Canada should visit our Tra...

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
What happens if I don’t pay my tuition fees on time? Are there penalties?

Top returned question:
What happens if someone on campus gets COVID?

Top returned answer:
The Return to Campus Guidelines highlights that while eliminating the COVID-19 virus will not occur in the near future, we can certainly adapt to living with COVID-19 as we do with other manageable seasonal ailments such as influenza. If someone in the community does contract COVID, the College will follow the public health guidelines provided by the PHO for reporting and notification. Preventing the spread of COVID-19 relies on everyone doing their part, including: immunization, daily self-admi...

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
How is my final grade determined, and can it be reviewed if I think it’s incorrect?

Top returned question:
What is an overaward and how do I repay it?

Top returned answer:
Find more information here: https://studentaidbc.ca/help-centre/applying-loans/why-do-i-have-overawardFor repayment of an overaward: https://studentaidbc.ca/help-centre/loan-repayment/how-do-i-repay-my-overaward

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
Can I book an appointment to discuss my course planning and academic goals?

Top returned question:
I’m not taking any classes this semester. Can I book an appointment?

Top returned answer:
You need to be a current Douglas College student registered in courses and residing in B.C. to book an appointment for personal or career counselling. If your program has a scheduled break (e.g. you are taking the Summer Semester off, but returning for Fall), then you remain eligible to book a counselling session during that break period.  Please note: if you need support related to academic probation, which has prevented you from registering for classes, please contact us (regardless of whether...

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

================================================================================
Query:
What kind of mental health or counselling services are available for students?

Top returned question:
Is counselling only for people with serious mental health concerns or diagnoses?

Top returned answer:
No! Counselling can be extremely helpful for dealing with everyday concerns that you might need support with, from stress about juggling your course load to struggles in a relationship.

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

Demi relevance judgments:
{'Is there a deadline I need to follow when applying to Douglas College programs?': [0], 'What happens if I don’t pay my tuition fees on time? Are there penalties?': [0], 'How is my final grade determined, and can it be reviewed if I think it’s incorrect?': [0], 'Can I book an appointment to discuss my course planning and academic goals?': [0], 'What kind of mental health or counselling services are available for students?': [1]}

Demi Precision@1 for each query: [0.0, 0.0, 0.0, 0.0, 1.0]
Demi Average Precision@1: 0.2

##### ==> Judgements of the relevant of the answers:
 
- Demi Part B Precision@1 scores: [0.0, 0.0, 0.0, 0.0,10.0]
- Demi Part B Average Precision@1: 0.2

##### ==> Judgements of the relevant of the answers:
- Ricardo Part B Precision@1 scores: [0.0, 1.0, 1.0, 1.0, 1.0]
- Ricardo Part B Average Precision@1: 0.8
- Hugh Part B Precision@1 scores: [0.0, 0.0, 0.0, 0.0, 0.0]
- Hugh Part B Average Precision@1: 0.0
- Demi Part B Precision@1 scores: [0.0, 0.0, 0.0, 0.0, 1.0]
- Demi Part B Average Precision@1: 0.2
- Jimmy Part B Precision@1 scores: [0.0, 1.0, 0.0, 0.0, 0.0]
- Jimmy Part B Average Precision@1: 0.2

# Part C. ElasticSearch with Embedding

### 1. Discussion

A keyword-based FAQBot can work well when the user uses the same words as the FAQ dataset, but it becomes weak when the question is written differently. In real use, students usually ask questions in their own way, so the wording may not exactly match the stored FAQ. Because of this, keyword search can miss relevant answers even when the meaning is very similar.

Another problem is that keyword search focuses more on overlapping words than actual intent. This can cause the system to return results that contain similar terms but discuss a different topic. For example, a question about application deadlines might retrieve a result about travelling to Canada if both contain related admission words. This makes the FAQBot less reliable for reworded, indirect, or conversational questions.

### 2. Building Embedding

In [15]:
nlp = spacy.load("en_core_web_lg")

In [16]:
def clean_text(text):
    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    return text

df["question_clean"] = df["question"].apply(clean_text)
df["answer_clean"] = df["answer"].apply(clean_text)
# df.info()

In [17]:
def get_embedding(text, nlp_model):
    return nlp_model(text).vector.astype(float)

df["question_vector"] = df["question_clean"].apply(lambda x: get_embedding(x, nlp))

VECTOR_DIMS = len(df["question_vector"].iloc[0])
print("Vector dimensions:", VECTOR_DIMS)

Vector dimensions: 300

In [18]:
index_name = "douglas_faq_vectors"

# Create a new index
if es.indices.exists(index=index_name):
    es.indices.delete(index=index_name)

mapping = {
    "mappings": {
        "properties": {
            "question": {
                "type": "text"
            },
            "answer": {
                "type": "text"
            },
            "question_clean": {
                "type": "text"
            },
            "question_vector": {
                "type": "dense_vector",
                "dims": VECTOR_DIMS,
                "index": True,
                "similarity": "cosine"
            }
        }
    }
}

es.indices.create(index=index_name, body=mapping)
# print(f"Created index: {index_name}")

ObjectApiResponse({'acknowledged': True, 'shards_acknowledged': True, 'index': 'douglas_faq_vectors'})

In [19]:
# Index all FAQ documents

actions = []

for i, row in df.iterrows():
    doc = {
        "question": row["question"],
        "answer": row["answer"],
        "question_clean": row["question_clean"],
        "question_vector": row["question_vector"].tolist()
    }

    es.index(
        index=index_name,
        id=i + 1,
        document=doc
    )

es.indices.refresh(index=index_name)

print(f"Indexed {len(df)} FAQ documents into Elasticsearch.")

Indexed 114 FAQ documents into Elasticsearch.

In [20]:
def semantic_search(query, es_client, index_name, nlp_model, top_k=5):
    query_clean = clean_text(query)
    query_vector = nlp_model(query_clean).vector.astype(float).tolist()

    response = es_client.search(
        index=index_name,
        body={
            "size": top_k,
            "query": {
                "script_score": {
                    "query": {"match_all": {}},
                    "script": {
                        "source": "cosineSimilarity(params.query_vector, 'question_vector') + 1.0",
                        "params": {
                            "query_vector": query_vector
                        }
                    }
                }
            }
        }
    )

    rows = []
    for hit in response["hits"]["hits"]:
        rows.append({
            "question": hit["_source"]["question"],
            "answer": hit["_source"]["answer"],
            "similarity_score": hit["_score"]
        })

    return pd.DataFrame(rows)

### 2. Testing + Evaluation

In [41]:
# Hugh - Part C testing + manual evaluation

hugh_test_questions = [
    "How can I submit my application?",
    "What do I need to pay for tuition?",
    "Where can I get advising help?",
    "How do I talk to a student advisor?",
    "What happens if I fail a course?"
]

hugh_results_c = []

for query in hugh_test_questions:
    results_df = semantic_search(query, es, index_name, nlp, top_k=5)

    if len(results_df) > 0:
        top_row = results_df.iloc[0]
        top_question = top_row["question"]
        top_answer = top_row["answer"]
        top_score = top_row["similarity_score"]
    else:
        top_question = "No result found"
        top_answer = "No answer found"
        top_score = 0

    hugh_results_c.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer,
        "similarity_score": top_score
    })
    
hugh_results_c_df = pd.DataFrame(hugh_results_c)
display(hugh_results_c_df)

# Ask for manual relevance with evidence
hugh_relevance_c = {}

for item in hugh_results_c:
    print("\n" + "=" * 90)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])
    print("\nSimilarity score:")
    print(item["similarity_score"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            hugh_relevance_c[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate Precision@1
hugh_p1_scores_c, hugh_avg_p1_c = evaluate_precision_at_1(hugh_relevance_c)

print("\nHugh Part C relevance judgments:")
print(hugh_relevance_c)
print("\nHugh Part C Precision@1 scores:", hugh_p1_scores_c)
print("Hugh Part C Average Precision@1:", hugh_avg_p1_c)

hugh_results_c_df = pd.DataFrame(hugh_results_c)
display(hugh_results_c_df)

,query,top_question,top_answer,similarity_score
0,How can I submit my application?,I got a letter saying I'm in the program. Why ...,The first letter you received was an acknowled...,0.917202
1,What do I need to pay for tuition?,If I have not made any payments towards my acc...,"Regardless of whether payment is made or not, ...",0.931566
2,Where can I get advising help?,How quickly can I get an appointment?,Counselling appointments are typically booked ...,0.919282
3,How do I talk to a student advisor?,I am almost done my program. How do I apply to...,You should apply to graduate after you have en...,0.917675
4,What happens if I fail a course?,What should I do if a have a final exam conflict?,"When the final exam schedule is published, som...",0.935441

==========================================================================================
Query:
How can I submit my application?

Top returned question:
I got a letter saying I'm in the program. Why do I have to submit any documents and/or do testing?

Top returned answer:
The first letter you received was an acknowledgment letter thanking you for your application and indicating it has been forwarded to an Admissions Officer for processing. The second letter you received outlined the admission requirements for the program to which you applied. Limited enrolment programs have specific admission requirements which must be completed before you can be admitted to the program. For details about specific programs, please refer to the Douglas College Catalog.

Similarity score:
0.9172021150588989

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
What do I need to pay for tuition?

Top returned question:
If I have not made any payments towards my account and I decide to drop courses once the semester starts, will I owe any fees?

Top returned answer:
Regardless of whether payment is made or not, you may owe the 50% tuition penalty for dropping courses during the 8th and 14th calendar day of the semester and if you drop the course after the first two weeks of the semester you will owe 100% of the course tuition.  The amount owed will be determined by the date and number of credits dropped.

Similarity score:
0.9315664172172546

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
Where can I get advising help?

Top returned question:
How quickly can I get an appointment?

Top returned answer:
Counselling appointments are typically booked one to two weeks ahead, and certain times of the semester are busier than others. If you are in crisis or concerned for your safety, please explain your situation to reception when you phone and request a “same-day urgent appointment.” We have a few time slots set aside each day for urgent situations. We do not maintain a cancellation list; if you have a time-sensitive matter that is not eligible for an urgent appointment, we invite you to sit in the...

Similarity score:
0.9192818403244019

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
How do I talk to a student advisor?

Top returned question:
I am almost done my program. How do I apply to graduate?

Top returned answer:
You should apply to graduate after you have enrolled in your final term of courses. You can apply by completing the online graduation application found on myAccount under "Student Records". Learn more from our graduation page.

Similarity score:
0.9176748991012573

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
What happens if I fail a course?

Top returned question:
What should I do if a have a final exam conflict?

Top returned answer:
When the final exam schedule is published, some students may find they have conflicting exam times or have too many exams within a short period of time. Consult the list below to see if you qualify to have your exam conflict resolved. If so, one of your instructors should be contacting you, but if they do not, please inform them you have an exam conflict so they can work with you to resolve it.Final Examinations will be rescheduled for any student with:Two (2) or more examinations at the same ti...

Similarity score:
0.9354411363601685

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

Hugh Part C relevance judgments:
{'How can I submit my application?': [1], 'What do I need to pay for tuition?': [0], 'Where can I get advising help?': [0], 'How do I talk to a student advisor?': [0], 'What happens if I fail a course?': [0]}

Hugh Part C Precision@1 scores: [1.0, 0.0, 0.0, 0.0, 0.0]
Hugh Part C Average Precision@1: 0.2

,query,top_question,top_answer,similarity_score
0,How can I submit my application?,I got a letter saying I'm in the program. Why ...,The first letter you received was an acknowled...,0.917202
1,What do I need to pay for tuition?,If I have not made any payments towards my acc...,"Regardless of whether payment is made or not, ...",0.931566
2,Where can I get advising help?,How quickly can I get an appointment?,Counselling appointments are typically booked ...,0.919282
3,How do I talk to a student advisor?,I am almost done my program. How do I apply to...,You should apply to graduate after you have en...,0.917675
4,What happens if I fail a course?,What should I do if a have a final exam conflict?,"When the final exam schedule is published, som...",0.935441

In [40]:
# Ricardo - Part C testing + manual evaluation

ricardo_questions_c = [
    "If I arrive late in Canada, can I study online first?",
    "My health insurance will end soon. Who should I talk to?",
    "I need help paying for school. Where can I ask about financial support?",
    "If I get sick and miss class, how can I ask my instructor for help?",
    "I want to transfer later to a university. Who can help me plan my courses?"
]

ricardo_results_c = []

for query in ricardo_questions_c:
    results_df = semantic_search(query, es, index_name, nlp, top_k=5)

    if len(results_df) > 0:
        top_row = results_df.iloc[0]
        top_question = top_row["question"]
        top_answer = top_row["answer"]
        top_score = top_row["similarity_score"]
    else:
        top_question = "No result found"
        top_answer = "Nqo answer found"
        top_score = 0

    ricardo_results_c.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer,
        "similarity_score": top_score
    })

# Ask for manual relevance with evidence
ricardo_relevance_c = {}

for item in ricardo_results_c:
    print("\n" + "=" * 90)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])
    print("\nSimilarity score:")
    print(item["similarity_score"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            ricardo_relevance_c[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate Precision@1
ricardo_p1_scores_c, ricardo_avg_p1_c = evaluate_precision_at_1(ricardo_relevance_c)

print("\nRicardo Part C relevance judgments:")
print(ricardo_relevance_c)
print("\nRicardo Part C Precision@1 scores:", ricardo_p1_scores_c)
print("Ricardo Part C Average Precision@1:", ricardo_avg_p1_c)

ricardo_results_c_df = pd.DataFrame(ricardo_results_c)
display(ricardo_results_c_df)

==========================================================================================
Query:
If I arrive late in Canada, can I study online first?

Top returned question:
I have not yet arrived in Canada, can I start classes online in my country?

Top returned answer:
The majority of courses in the Winter 2022 semester at Douglas College are currently scheduled to be in-person. Classes that are scheduled as “in-person” or “hybrid” require students to be here from the beginning of the semester. If none of your classes have in-class components that required you to be on campus and you choose to study online from your country, please review these considerations: Some courses have scheduled times and students are expected to be online in the sessions Please accou...

Similarity score:
0.9527471661567688

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
My health insurance will end soon. Who should I talk to?

Top returned question:
My medical insurance is expiring. What should I do?

Top returned answer:
If your medical insurance is expiring, now is the time to ensure you are covered. For information on medical insurance for international students, please visit this page for options.

Similarity score:
0.9331274032592773

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
I need help paying for school. Where can I ask about financial support?

Top returned question:
How do I receive my BC student loan funding once I have registered for classes?

Top returned answer:
Douglas College will need to confirm your enrolment in order for your student loan funds to be disbursedRegister in at least 9 credits of post-secondary level courses for Full-time loans. Not eligible for a student loan:Upgrading courses such as ENGU/ELLA and MATU.Courses that start with a zero (e.g., HUMD 0130). Repeating courses that you have passed with a grade of "P" or higher. (Unless approved repeat course appeal by SABC)Courses that you are auditing.Prior Learning Assessment and Recogniti...

Similarity score:
0.9315986037254333

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
If I get sick and miss class, how can I ask my instructor for help?

Top returned question:
Do I need to prepare anything for my appointment?

Top returned answer:
No, you do not need to prepare anything. However, we advise you to read the Information and Consent to Counsel Form prior to your session. Your counsellor will go over this when you arrive, so it will speed up the process if you are already familiar with it.

Similarity score:
0.9315723776817322

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
I want to transfer later to a university. Who can help me plan my courses?

Top returned question:
I'm interested in transferring to a university, how should I plan my courses?

Top returned answer:
Please review our University Transfer page for more information on how to plan for your transfer.  We encourage students to meet with a Student Success Advisor early to plan a successful transfer.

Similarity score:
0.9513794183731079

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

Ricardo Part C relevance judgments:
{'If I arrive late in Canada, can I study online first?': [1], 'My health insurance will end soon. Who should I talk to?': [1], 'I need help paying for school. Where can I ask about financial support?': [0], 'If I get sick and miss class, how can I ask my instructor for help?': [0], 'I want to transfer later to a university. Who can help me plan my courses?': [1]}

Ricardo Part C Precision@1 scores: [1.0, 1.0, 0.0, 0.0, 1.0]
Ricardo Part C Average Precision@1: 0.6

,query,top_question,top_answer,similarity_score
0,"If I arrive late in Canada, can I study online...","I have not yet arrived in Canada, can I start ...",The majority of courses in the Winter 2022 sem...,0.952747
1,My health insurance will end soon. Who should ...,My medical insurance is expiring. What should ...,"If your medical insurance is expiring, now is ...",0.933127
2,I need help paying for school. Where can I ask...,How do I receive my BC student loan funding on...,Douglas College will need to confirm your enro...,0.931599
3,"If I get sick and miss class, how can I ask my...",Do I need to prepare anything for my appointment?,"No, you do not need to prepare anything. Howev...",0.931572
4,I want to transfer later to a university. Who ...,I'm interested in transferring to a university...,Please review our University Transfer page for...,0.951379

In [23]:

demi_questions_c = [
    "Is there a deadline I need to follow when applying to Douglas College programs?",
    "What happens if I don’t pay my tuition fees on time? Are there penalties?",
    "How is my final grade determined, and can it be reviewed if I think it’s incorrect?",
    "Can I book an appointment to discuss my course planning and academic goals?",
    "What kind of mental health or counselling services are available for students?"
]

demi_results_c = []

for query in demi_questions_c:
    results_df = semantic_search(query, es, index_name, nlp, top_k=5)

    if len(results_df) > 0:
        top_row = results_df.iloc[0]
        top_question = top_row["question"]
        top_answer = top_row["answer"]
        top_score = top_row["similarity_score"]
    else:
        top_question = "No result found"
        top_answer = "No answer found"
        top_score = 0

    demi_results_c.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer,
        "similarity_score": top_score
    })

# Ask for manual relevance with evidence
demi_relevance_c = {}

for item in demi_results_c:
    print("\n" + "=" * 90)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])
    print("\nSimilarity score:")
    print(item["similarity_score"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            demi_relevance_c[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate Precision@1
demi_p1_scores_c, demi_avg_p1_c = evaluate_precision_at_1(demi_relevance_c)

print("\nDemi Part C relevance judgments:")
print(demi_relevance_c)
print("\nDemi Part C Precision@1 scores:", demi_p1_scores_c)
print("Demi Part C Average Precision@1:", demi_avg_p1_c)

demi_results_c_df = pd.DataFrame(demi_results_c)
display(demi_results_c_df)

==========================================================================================
Query:
Is there a deadline I need to follow when applying to Douglas College programs?

Top returned question:
I am out of the country, when should I come to BC and what is required by Douglas College?

Top returned answer:
Classes that are scheduled as “in-person” or “hybrid” require students to be here from the beginning of the semester. Unless your country has a travel ban and you are able to study online, you should plan to arrive in Canada at least 14 days before classes start to complete quarantine if required. Travel planning: a. You can travel to Canada as an international student if you have a valid study permit or have been approved for a study permit. b. Students travelling to Canada should visit our Tra...

Similarity score:
1.9433601

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
What happens if I don’t pay my tuition fees on time? Are there penalties?

Top returned question:
If I have not made any payments towards my account and I decide to drop courses once the semester starts, will I owe any fees?

Top returned answer:
Regardless of whether payment is made or not, you may owe the 50% tuition penalty for dropping courses during the 8th and 14th calendar day of the semester and if you drop the course after the first two weeks of the semester you will owe 100% of the course tuition.  The amount owed will be determined by the date and number of credits dropped.

Similarity score:
1.9468955

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
How is my final grade determined, and can it be reviewed if I think it’s incorrect?

Top returned question:
When will I hear that I have been accepted to or have a seat in the program?

Top returned answer:
You will receive a letter from Douglas College acknowledging your application to a limited enrolment program approximately two to three weeks after submission. An Admissions Officer will advise you in writing of all admission requirements for the selected program. You must successfully complete all of the minimum academic admission requirements and interview (if applicable). Once these requirements are met, your name will remain on the list for an available seat in the program. Offers are made b...

Similarity score:
1.9401475

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
Can I book an appointment to discuss my course planning and academic goals?

Top returned question:
What information do I need to provide to book an appointment?

Top returned answer:
Your name, student number, the type of counselling – personal, career or academic – you are seeking support for and a brief explanation of your concerns. Refer to the list of statements on our counselling home page for examples of counselling topics. If you have concerns for your safety or the matter is time-sensitive, please let reception know.

Similarity score:
1.9311564

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
What kind of mental health or counselling services are available for students?

Top returned question:
Is counselling only for people with serious mental health concerns or diagnoses?

Top returned answer:
No! Counselling can be extremely helpful for dealing with everyday concerns that you might need support with, from stress about juggling your course load to struggles in a relationship.

Similarity score:
1.9376235

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

Demi Part C relevance judgments:
{'Is there a deadline I need to follow when applying to Douglas College programs?': [0], 'What happens if I don’t pay my tuition fees on time? Are there penalties?': [1], 'How is my final grade determined, and can it be reviewed if I think it’s incorrect?': [0], 'Can I book an appointment to discuss my course planning and academic goals?': [1], 'What kind of mental health or counselling services are available for students?': [1]}

Demi Part C Precision@1 scores: [0.0, 1.0, 0.0, 1.0, 1.0]
Demi Part C Average Precision@1: 0.6

,query,top_question,top_answer,similarity_score
0,Is there a deadline I need to follow when appl...,"I am out of the country, when should I come to...",Classes that are scheduled as “in-person” or “...,1.943360
1,What happens if I don’t pay my tuition fees on...,If I have not made any payments towards my acc...,"Regardless of whether payment is made or not, ...",1.946895
2,"How is my final grade determined, and can it b...",When will I hear that I have been accepted to ...,You will receive a letter from Douglas College...,1.940147
3,Can I book an appointment to discuss my course...,What information do I need to provide to book ...,"Your name, student number, the type of counsel...",1.931156
4,What kind of mental health or counselling serv...,Is counselling only for people with serious me...,No! Counselling can be extremely helpful for d...,1.937623

In [24]:
# Jimmy - Part C testing + manual evaluation

Jimmy_test_questions = [
    "What is the best way to contact Enrollment Services?",
    "How do i update my personal information?",
    "Who do i contact if i have questions about Co-op?",
    "What if i want to take a course from another university/college?",
    "What happens if i withdraw from a course?"
]

Jimmy_results_c = []

for query in Jimmy_test_questions:
    results_df = semantic_search(query, es, index_name, nlp, top_k=5)

    if len(results_df) > 0:
        top_row = results_df.iloc[0]
        top_question = top_row["question"]
        top_answer = top_row["answer"]
        top_score = top_row["similarity_score"]
    else:
        top_question = "No result found"
        top_answer = "No answer found"
        top_score = 0

    Jimmy_results_c.append({
        "query": query,
        "top_question": top_question,
        "top_answer": top_answer,
        "similarity_score": top_score
    })
    
Jimmy_results_c_df = pd.DataFrame(Jimmy_results_c)
display(Jimmy_results_c_df)

# Ask for manual relevance with evidence
Jimmy_relevance_c = {}

for item in Jimmy_results_c:
    print("\n" + "=" * 90)
    print("Query:")
    print(item["query"])
    print("\nTop returned question:")
    print(item["top_question"])
    print("\nTop returned answer:")
    print(item["top_answer"][:500] + "..." if len(item["top_answer"]) > 500 else item["top_answer"])
    print("\nSimilarity score:")
    print(item["similarity_score"])

    while True:
        user_input = input("\nIs this top result relevant? Enter 1 = Yes, 0 = No: ").strip()
        if user_input in ["1", "0"]:
            Jimmy_relevance_c[item["query"]] = [int(user_input)]
            break
        else:
            print("Invalid input. Please enter only 1 or 0.")

# Evaluate Precision@1
Jimmy_p1_scores_c, Jimmy_avg_p1_c = evaluate_precision_at_1(Jimmy_relevance_c)

print("\nJimmy Part C relevance judgments:")
print(Jimmy_relevance_c)
print("\nJimmy Part C Precision@1 scores:", Jimmy_p1_scores_c)
print("Jimmy Part C Average Precision@1:", Jimmy_avg_p1_c)

Jimmy_results_c_df = pd.DataFrame(Jimmy_results_c)
display(Jimmy_results_c_df)

,query,top_question,top_answer,similarity_score
0,What is the best way to contact Enrollment Ser...,What information do I need to provide to book ...,"Your name, student number, the type of counsel...",1.915307
1,How do i update my personal information?,How do I update my mailing address for graduat...,You can update your mailing address and phone ...,1.941309
2,Who do i contact if i have questions about Co-op?,My International question wasn't answered by t...,"When contacting the international office, plea...",1.923811
3,What if i want to take a course from another u...,I'm interested in transferring to a university...,Please review our University Transfer page for...,1.952648
4,What happens if i withdraw from a course?,What should I do if a have a final exam conflict?,"When the final exam schedule is published, som...",1.934628

==========================================================================================
Query:
What is the best way to contact Enrollment Services?

Top returned question:
What information do I need to provide to book an appointment?

Top returned answer:
Your name, student number, the type of counselling – personal, career or academic – you are seeking support for and a brief explanation of your concerns. Refer to the list of statements on our counselling home page for examples of counselling topics. If you have concerns for your safety or the matter is time-sensitive, please let reception know.

Similarity score:
1.9153066

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
How do i update my personal information?

Top returned question:
How do I update my mailing address for graduation?

Top returned answer:
You can update your mailing address and phone number in myAccount under Personal Information. If you would like to update your name, complete a Name Change Request and submit it to Enrolment Services.

Similarity score:
1.9413089

Is this top result relevant? Enter 1 = Yes, 0 = No:  1

==========================================================================================
Query:
Who do i contact if i have questions about Co-op?

Top returned question:
My International question wasn't answered by this FAQ. Who do I contact?

Top returned answer:
When contacting the international office, please include your full legal name and student ID for verification. For information on our online services please visit our online services page or you can contact us via webform.

Similarity score:
1.9238113

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
What if i want to take a course from another university/college?

Top returned question:
I'm interested in transferring to a university, how should I plan my courses?

Top returned answer:
Please review our University Transfer page for more information on how to plan for your transfer.  We encourage students to meet with a Student Success Advisor early to plan a successful transfer.

Similarity score:
1.9526483

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

==========================================================================================
Query:
What happens if i withdraw from a course?

Top returned question:
What should I do if a have a final exam conflict?

Top returned answer:
When the final exam schedule is published, some students may find they have conflicting exam times or have too many exams within a short period of time. Consult the list below to see if you qualify to have your exam conflict resolved. If so, one of your instructors should be contacting you, but if they do not, please inform them you have an exam conflict so they can work with you to resolve it.Final Examinations will be rescheduled for any student with:Two (2) or more examinations at the same ti...

Similarity score:
1.9346279

Is this top result relevant? Enter 1 = Yes, 0 = No:  0

Jimmy Part C relevance judgments:
{'What is the best way to contact Enrollment Services?': [1], 'How do i update my personal information?': [1], 'Who do i contact if i have questions about Co-op?': [0], 'What if i want to take a course from another university/college?': [0], 'What happens if i withdraw from a course?': [0]}

Jimmy Part C Precision@1 scores: [1.0, 1.0, 0.0, 0.0, 0.0]
Jimmy Part C Average Precision@1: 0.4

,query,top_question,top_answer,similarity_score
0,What is the best way to contact Enrollment Ser...,What information do I need to provide to book ...,"Your name, student number, the type of counsel...",1.915307
1,How do i update my personal information?,How do I update my mailing address for graduat...,You can update your mailing address and phone ...,1.941309
2,Who do i contact if i have questions about Co-op?,My International question wasn't answered by t...,"When contacting the international office, plea...",1.923811
3,What if i want to take a course from another u...,I'm interested in transferring to a university...,Please review our University Transfer page for...,1.952648
4,What happens if i withdraw from a course?,What should I do if a have a final exam conflict?,"When the final exam schedule is published, som...",1.934628

##### ==> Judgements of the relevant of the answers:
- Ricardo Part C Precision@1 scores: [1.0, 1.0, 0.0, 0.0, 1.0]
- Ricardo Part C Average Precision@1: 0.6
- Hugh Part C Precision@1 scores: [1.0, 0.0, 0.0, 0.0, 0.0]
- Hugh Part C Average Precision@1: 0.2
- Demi Part C Precision@1 scores: [0.0, 1.0, 0.0, 1.0, 1.0]
- Demi Part C Average Precision@1: 0.6
- Jimmy Part C Precision@1 scores: [1.0, 1.0, 0.0, 0.0, 0.0]
- Jimmy Part C Average Precision@1: 0.4

# Part D. FAQBot using Gemini

### 1. RAG Building

In [43]:
# Initialize the client with API key
client = genai.Client(api_key="AIzaSyCwcQw4ReLIS-1mgkwxuKX3AGPdGwcqS8E")

In [44]:
# Create a file search store for FAQ documents
# file_search_store = client.file_search_stores.create(
#     config={"display_name": "faq-documents"}
# )
# print(f"Created store: {file_search_store.name}")

In [45]:
# Clean text helper

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [46]:
# Build local FAQ corpus for Part D

faq_gemini_df = df[["question", "answer"]].dropna().drop_duplicates().reset_index(drop=True)
print("Total FAQ rows available for Part D:", len(faq_gemini_df))
faq_gemini_df.head()

Total FAQ rows available for Part D: 114

,question,answer
0,How many programs can I apply to?,You can indicate one program choice per applic...
1,What is the fee to apply?,$37.40 for Canadian/Permanent Residents. $100 ...
2,What is preferential admission?,Preferential admission is a selective admissio...
3,How long is the wait-list for Douglas College ...,There is no wait-list for open enrolment or li...
4,I got a letter saying I'm in the program. Why ...,The first letter you received was an acknowled...

In [47]:
# # Upload and index FAQ documents
# faq_documents = ["faq.csv", "faq1.csv", 
#                  "faq2.csv", "faq3.csv",
#                  "faq4.csv", "faq5.csv", 
#                  "faq6.csv", "faq7.csv"]

# for faq_document in faq_documents:
#     operation = client.file_search_stores.upload_to_file_search_store(
#         file=faq_document,
#         file_search_store_name=file_search_store.name,
#         config={"display_name": faq_document.replace(".csv", "")},
#     )
#     while not operation.done:
#         time.sleep(3)
#         operation = client.operations.get(operation)
#     print(f"{faq_document} indexed")

In [48]:
# Build local vectors for FAQ questions

faq_gemini_df["question_clean"] = faq_gemini_df["question"].apply(clean_text)
faq_gemini_df["question_vector"] = faq_gemini_df["question_clean"].apply(lambda x: nlp(x).vector)

print("Local question vectors created for Part D.")

Local question vectors created for Part D.

In [49]:
# from pathlib import Path
# import time

# faq_documents = [
#     "faq.csv", "faq1.csv", "faq2.csv", "faq3.csv",
#     "faq4.csv", "faq5.csv", "faq6.csv", "faq7.csv"
# ]

# for faq_document in faq_documents:
#     file_path = Path(faq_document).resolve()

#     if not file_path.exists():
#         print(f"File not found: {file_path}")
#         continue

#     # Step 1: upload to Files API
#     uploaded_file = client.files.upload(
#         file=str(file_path),
#         config={"display_name": file_path.stem}
#     )

#     print(f"Uploaded to Files API: {uploaded_file.name}")

#     # Step 2: import that file into the File Search store
#     operation = client.file_search_stores.import_file(
#         file_search_store_name=file_search_store.name,
#         file_name=uploaded_file.name
#     )

#     while not operation.done:
#         time.sleep(3)
#         operation = client.operations.get(operation)

#     print(f"{file_path.name} indexed via Files API -> import_file")

In [50]:
# from pathlib import Path
# import time
# import random
# from google.genai import errors

# # Upload one file using Files API, then import it into the File Search store
# def upload_csv_to_store_with_retry(file_path, store_name, max_retries=5):
#     file_path = Path(file_path).resolve()

#     if not file_path.exists():
#         raise FileNotFoundError(f"File not found: {file_path}")

#     last_error = None

#     for attempt in range(max_retries):
#         try:
#             # Step 1: upload file
#             uploaded_file = client.files.upload(
#                 file=str(file_path),
#                 config={"display_name": file_path.stem}
#             )

#             # Step 2: import uploaded file into the store
#             operation = client.file_search_stores.import_file(
#                 file_search_store_name=store_name,
#                 file_name=uploaded_file.name
#             )

#             # Wait until import finishes
#             while not operation.done:
#                 time.sleep(3)
#                 operation = client.operations.get(operation)

#             return operation

#         except errors.ServerError as e:
#             last_error = e
#             wait_time = (2 ** attempt) + random.random()
#             print(f"Server error for {file_path.name}. Retry {attempt + 1}/{max_retries} in {wait_time:.1f}s")
#             time.sleep(wait_time)

#     raise last_error


# # Upload and index FAQ documents
# faq_documents = [
#     "faq.csv", "faq1.csv", "faq2.csv", "faq3.csv",
#     "faq4.csv", "faq5.csv", "faq6.csv", "faq7.csv"
# ]

# for faq_document in faq_documents:
#     operation = upload_csv_to_store_with_retry(
#         file_path=faq_document,
#         store_name=file_search_store.name,
#         max_retries=5
#     )
#     print(f"{faq_document} indexed")

In [51]:
# Local semantic search
# This keeps the same function style used in the project, but the retrieval is local.

es = None
index_name = "local_part_d"

def semantic_search(query, es_client, index_name, nlp_model, top_k=5):
    query_clean = clean_text(query)
    query_vector = nlp_model(query_clean).vector

    rows = []
    for _, row in faq_gemini_df.iterrows():
        doc_vector = row["question_vector"]

        query_norm = np.linalg.norm(query_vector)
        doc_norm = np.linalg.norm(doc_vector)

        if query_norm == 0 or doc_norm == 0:
            score = 0.0
        else:
            score = float(np.dot(query_vector, doc_vector) / (query_norm * doc_norm))

        rows.append({
            "question": row["question"],
            "answer": row["answer"],
            "similarity_score": score
        })

    results_df = pd.DataFrame(rows).sort_values(
        by="similarity_score", ascending=False
    ).head(top_k).reset_index(drop=True)

    return results_df

In [52]:
# Part D retrieval helper (local RAG)

def retrieve_faq_context(query, top_k=3):
    return semantic_search(query, es, index_name, nlp, top_k=top_k)

In [53]:
# Define system instructions
SYSTEM_INSTRUCTION = """
You are 'FAQBOT', a helpful assistant that answers questions based on indexed documents.
Provide concise, accurate information from the knowledge base.
If you don't know the answer, politely say so.
"""

In [54]:
# # Create chat session with file search capability
# def get_response(query):
#     response = client.models.generate_content(
#         model="gemini-2.5-flash",
#         contents=[
#             {"role": "system", "parts": [SYSTEM_INSTRUCTION]},
#             {"role": "user", "parts": [query]}
#         ],
#         config=types.GenerateContentConfig(
#             tools=[
#                 types.Tool(
#                     file_search=types.FileSearch(
#                         file_search_store_names=[file_search_store.name]
#                     )
#                 )
#             ]
#         ),
#     )
#     return response.text

In [55]:
# Create chat response function with local retrieval instead of File Search Store

def get_response(query, top_k=3):
    retrieved_df = retrieve_faq_context(query, top_k=top_k)

    if len(retrieved_df) == 0:
        return {
            "query": query,
            "top_question": "No result found",
            "top_answer": "No answer found",
            "gemini_answer": "The information is not clear from the FAQ.",
            "retrieved_df": pd.DataFrame()
        }

    context_blocks = []
    for _, row in retrieved_df.iterrows():
        context_blocks.append(
            f"FAQ Question: {row['question']}\nFAQ Answer: {row['answer']}"
        )

    context_text = "\n\n".join(context_blocks)

    prompt = (
        SYSTEM_INSTRUCTION
        + "\n\nUser question:\n"
        + query
        + "\n\nFAQ context:\n"
        + context_text
        + "\n\nAnswer the user question using only the FAQ context. Keep the answer short and clear."
    )

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    top_row = retrieved_df.iloc[0]

    return {
        "query": query,
        "top_question": top_row["question"],
        "top_answer": top_row["answer"],
        "gemini_answer": response.text,
        "retrieved_df": retrieved_df
    }

In [56]:
# print("--- Welcome to FAQBOT! (Type 'quit' to exit) ---")
# while True:
#     user_input = input("You: ")
#     if user_input.lower() in ["quit", "exit", "bye"]:
#         print("FAQBOT: Goodbye! Have a great day.")
#         break
    
#     # Get response with full response object
#     full_response = client.models.generate_content(
#         model="gemini-2.5-flash",
#         contents=user_input,  
#         config=types.GenerateContentConfig(
#             tools=[types.Tool(file_search=types.FileSearch(file_search_store_names=[file_search_store.name]))],
#             system_instruction=SYSTEM_INSTRUCTION + """
#             Format your responses with clear section separators:
#             1. Place a line of dashes (---) between each major section or topic
#             2. For example, separate "Official Transcripts" and "Unofficial Transcripts" with a separator
#             3. Make sure information is clearly organized and easy to read
#             """
#         ),
#     )
#     print(f"FAQBOT: {full_response.text}")
#     print("-" * 50)
    
#     # Display sources if available 
#     try:
#         metadata = full_response.candidates[0].grounding_metadata
#         unique_sources = set()
        
#         print("Sources consulted:")
#         for i, chunk in enumerate(metadata.grounding_chunks, 1):
#             source_title = chunk.retrieved_context.title
#             if source_title not in unique_sources:
#                 unique_sources.add(source_title)
#                 print(f"  [{len(unique_sources)}] {source_title}")
#     except:
#         print("No specific sources cited.")
    
#     print("-" * 50)

### 2. Testing + Evaluation

In [57]:
print("--- Welcome to FAQBOT! (Type 'quit' to exit) ---")

while True:
    user_input = input("You: ")
    if user_input.lower() in ["quit", "exit", "bye"]:
        print("FAQBOT: Goodbye! Have a great day.")
        break

    full_response = get_response(user_input, top_k=3)

    print("\nTop retrieved question:")
    print(full_response["top_question"])

    print("\nFAQBOT:")
    print(full_response["gemini_answer"])

    print("-" * 50)

--- Welcome to FAQBOT! (Type 'quit' to exit) ---

You:  Is there a deadline I need to follow when applying to Douglas College programs?

Top retrieved question:
I am out of the country, when should I come to BC and what is required by Douglas College?

FAQBOT:
I don't have information about application deadlines for Douglas College programs in the provided context.
--------------------------------------------------

You:  What happens if I don’t pay my tuition fees on time? Are there penalties?

Top retrieved question:
If I have not made any payments towards my account and I decide to drop courses once the semester starts, will I owe any fees?

FAQBOT:
I apologize, but I cannot find information in the provided FAQ context about what happens if you don’t pay your tuition fees on time or if there are penalties specifically for late payment. The context discusses penalties for dropping courses and information about student loans and tax deductions.
--------------------------------------------------

You:  How is my final grade determined, and can it be reviewed if I think it’s incorrect?

Top retrieved question:
When will I hear that I have been accepted to or have a seat in the program?

FAQBOT:
I apologize, but the provided FAQ context does not contain information on how final grades are determined or if they can be reviewed.
--------------------------------------------------

You:  Can I book an appointment to discuss my course planning and academic goals?

Top retrieved question:
What information do I need to provide to book an appointment?

FAQBOT:
Yes, you can book an appointment to discuss academic goals and course planning. The FAQ mentions "academic counselling" as a type of support you can seek, and you are welcome to bring up any topic of concern.
--------------------------------------------------

You:  What kind of mental health or counselling services are available for students?

Top retrieved question:
Is counselling only for people with serious mental health concerns or diagnoses?

FAQBOT:
Counselling services are available for students through the Counselling Department. Counsellors can help with a variety of concerns, including everyday issues like stress from course load, relationship struggles, feeling down and unmotivated, making future life choices, academic struggles, navigating academic probation, and requesting exceptions for course withdrawals. Counselling is helpful for various concerns, not just serious mental health diagnoses.
--------------------------------------------------

You:  What is the best way to contact Enrollment Services?,

Top retrieved question:
What information do I need to provide to book an appointment?

FAQBOT:
To contact Enrollment Services, visit your myAccount to find the contact information for your Student Success Advisor in Enrolment Services.
--------------------------------------------------

You:  How do i update my personal information?,

Top retrieved question:
How do I update my mailing address for graduation?

FAQBOT:
You can update your mailing address and phone number in myAccount under Personal Information. To update your name, complete a Name Change Request and submit it to Enrolment Services.
--------------------------------------------------

You:  Who do i contact if i have questions about Co-op?,

Top retrieved question:
My International question wasn't answered by this FAQ. Who do I contact?

FAQBOT:
I apologize, but I cannot find information about who to contact for Co-op questions in the provided FAQ context.
--------------------------------------------------

You:  What if i want to take a course from another university/college?,

Top retrieved question:
I'm interested in transferring to a university, how should I plan my courses?

FAQBOT:
If you are asking about getting credit at Douglas College for courses you have taken at another institution, Transfer Credit is possible. You can consult the BC Transfer Guide to see if a course transfers to/from Douglas College and review the Transfer Credit page for more information on initiating the process.
--------------------------------------------------

You:  What happens if i withdraw from a course?

Top retrieved question:
If I have not made any payments towards my account and I decide to drop courses once the semester starts, will I owe any fees?

FAQBOT:
If you drop courses during the 8th and 14th calendar day of the semester, you may owe a 50% tuition penalty. If you drop a course after the first two weeks of the semester, you will owe 100% of the course tuition. The amount owed is determined by the date and number of credits dropped.
--------------------------------------------------

You:  quit

FAQBOT: Goodbye! Have a great day.

##### ==> Judgements of the relevant of the answers:
- Ricardo Part D Precision@1 scores: [1.0, 1.0, 0.0, 1.0, 1.0]
- Ricardo Part D Average Precision@1: 0.8
- Demi Part D Precision@1 scores: [0.0, 0.0, 0.0, 1.0, 1.0]
- Demi Part D Average Precision@1: 0.4
- Hugh Part D Precision@1 scores: [1.0, 0.0, 0.0, 0.0, .0]
- Hugh Part D Average Precision@1: 0.2
- Jimmy Part D Precision@1 scores: [1.0, 1.0, 0.0, 1.0, 1.0]
- Jimmy Part D Average Precision@1: 0.8

# Part E. Final Conclusion + Compare Results

### Part B: Elasticsearch (Keyword-Based Search)
The keyword-based approach shows inconsistent performance across different question sets. While it performs relatively well for Ricardo’s questions (Average Precision@1 = 0.8), it fails completely for Hugh (0.0) and performs poorly for Demi and Jimmy (both 0.2). This indicates that keyword search is highly dependent on exact word matching. When user queries are phrased differently from the stored FAQs, the system struggles to retrieve relevant answers, often returning results from incorrect topics.

### Part C: Elasticsearch + Embeddings (Semantic Search)
The addition of embeddings improves performance by capturing semantic similarity rather than relying solely on keywords. This is reflected in higher scores for Demi (0.6) and Ricardo (0.6), compared to Part B. However, the performance is still uneven, especially for Hugh (0.2) and Jimmy (0.4). While semantic search helps with reworded queries, it can still produce mismatches when different topics share similar contextual language.

### Part D: FAQBot with Gemini (RAG Approach)
The RAG-based approach using Gemini demonstrates the strongest and most consistent performance overall. Ricardo and Jimmy both achieve high scores (0.8), while Demi improves compared to Part B (0.4). Although Hugh’s results remain relatively low (0.2), the overall trend shows that combining retrieval with generation helps the system better interpret user intent and produce more relevant responses.

### Conclusion
The evaluation shows that moving from keyword-based search to semantic search and finally to a RAG-based system significantly improves the quality of the FAQBot. While no approach achieves perfect accuracy, the RAG model provides the most robust and user-friendly performance, especially for natural and conversational queries.

# Member Contribution

| Name       | Demi   | Ricardo | Jimmy   | Hugh   |
|------------|--------|---------|---------|--------|
|   Demi     | *****  |4        |4        |4       |
|   Ricardo  |4       |  *****  |4        |4       |
|   Jimmy    | 4      |4        |  *****  |4       |
|   Hugh     | 4      |4        |4        |  ***** |

#